//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.SR_StudentWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/StudentData")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataLayer.SR_StudentWcf.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataLayer.SR_StudentWcf.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/StudentData")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_StudentWcf.IWcfServiceDefinition")]
    public interface IWcfServiceDefinition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDefinition/QueryStudents", ReplyAction="http://tempuri.org/IWcfServiceDefinition/QueryStudentsResponse")]
        System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student> QueryStudents();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfServiceDefinition/QueryStudents", ReplyAction="http://tempuri.org/IWcfServiceDefinition/QueryStudentsResponse")]
        System.IAsyncResult BeginQueryStudents(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student> EndQueryStudents(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceDefinitionChannel : DataLayer.SR_StudentWcf.IWcfServiceDefinition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceDefinitionClient : System.ServiceModel.ClientBase<DataLayer.SR_StudentWcf.IWcfServiceDefinition>, DataLayer.SR_StudentWcf.IWcfServiceDefinition {
        
        private BeginOperationDelegate onBeginQueryStudentsDelegate;
        
        private EndOperationDelegate onEndQueryStudentsDelegate;
        
        private System.Threading.SendOrPostCallback onQueryStudentsCompletedDelegate;
        
        public WcfServiceDefinitionClient() {
        }
        
        public WcfServiceDefinitionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceDefinitionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceDefinitionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceDefinitionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<QueryStudentsCompletedEventArgs> QueryStudentsCompleted;
        
        public System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student> QueryStudents() {
            return base.Channel.QueryStudents();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQueryStudents(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryStudents(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student> EndQueryStudents(System.IAsyncResult result) {
            return base.Channel.EndQueryStudents(result);
        }
        
        private System.IAsyncResult OnBeginQueryStudents(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginQueryStudents(callback, asyncState);
        }
        
        private object[] OnEndQueryStudents(System.IAsyncResult result) {
            System.Collections.Generic.List<DataLayer.SR_StudentWcf.Student> retVal = this.EndQueryStudents(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryStudentsCompleted(object state) {
            if ((this.QueryStudentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryStudentsCompleted(this, new QueryStudentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryStudentsAsync() {
            this.QueryStudentsAsync(null);
        }
        
        public void QueryStudentsAsync(object userState) {
            if ((this.onBeginQueryStudentsDelegate == null)) {
                this.onBeginQueryStudentsDelegate = new BeginOperationDelegate(this.OnBeginQueryStudents);
            }
            if ((this.onEndQueryStudentsDelegate == null)) {
                this.onEndQueryStudentsDelegate = new EndOperationDelegate(this.OnEndQueryStudents);
            }
            if ((this.onQueryStudentsCompletedDelegate == null)) {
                this.onQueryStudentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryStudentsCompleted);
            }
            base.InvokeAsync(this.onBeginQueryStudentsDelegate, null, this.onEndQueryStudentsDelegate, this.onQueryStudentsCompletedDelegate, userState);
        }
    }
}
