//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.SR_PersonAsmx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataLayer.SR_PersonAsmx.Address AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DataLayer.SR_PersonAsmx.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_PersonAsmx.AsmxServiceSoap")]
    public interface AsmxServiceSoap {
        
        // CODEGEN: Generating message contract since element name QueryPersonsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPersons", ReplyAction="*")]
        DataLayer.SR_PersonAsmx.QueryPersonsResponse QueryPersons(DataLayer.SR_PersonAsmx.QueryPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/QueryPersons", ReplyAction="*")]
        System.IAsyncResult BeginQueryPersons(DataLayer.SR_PersonAsmx.QueryPersonsRequest request, System.AsyncCallback callback, object asyncState);
        
        DataLayer.SR_PersonAsmx.QueryPersonsResponse EndQueryPersons(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryPersons", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.SR_PersonAsmx.QueryPersonsRequestBody Body;
        
        public QueryPersonsRequest() {
        }
        
        public QueryPersonsRequest(DataLayer.SR_PersonAsmx.QueryPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class QueryPersonsRequestBody {
        
        public QueryPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryPersonsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataLayer.SR_PersonAsmx.QueryPersonsResponseBody Body;
        
        public QueryPersonsResponse() {
        }
        
        public QueryPersonsResponse(DataLayer.SR_PersonAsmx.QueryPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person> QueryPersonsResult;
        
        public QueryPersonsResponseBody() {
        }
        
        public QueryPersonsResponseBody(System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person> QueryPersonsResult) {
            this.QueryPersonsResult = QueryPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsmxServiceSoapChannel : DataLayer.SR_PersonAsmx.AsmxServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryPersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryPersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsmxServiceSoapClient : System.ServiceModel.ClientBase<DataLayer.SR_PersonAsmx.AsmxServiceSoap>, DataLayer.SR_PersonAsmx.AsmxServiceSoap {
        
        private BeginOperationDelegate onBeginQueryPersonsDelegate;
        
        private EndOperationDelegate onEndQueryPersonsDelegate;
        
        private System.Threading.SendOrPostCallback onQueryPersonsCompletedDelegate;
        
        public AsmxServiceSoapClient() {
        }
        
        public AsmxServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsmxServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<QueryPersonsCompletedEventArgs> QueryPersonsCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.SR_PersonAsmx.QueryPersonsResponse DataLayer.SR_PersonAsmx.AsmxServiceSoap.QueryPersons(DataLayer.SR_PersonAsmx.QueryPersonsRequest request) {
            return base.Channel.QueryPersons(request);
        }
        
        public System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person> QueryPersons() {
            DataLayer.SR_PersonAsmx.QueryPersonsRequest inValue = new DataLayer.SR_PersonAsmx.QueryPersonsRequest();
            inValue.Body = new DataLayer.SR_PersonAsmx.QueryPersonsRequestBody();
            DataLayer.SR_PersonAsmx.QueryPersonsResponse retVal = ((DataLayer.SR_PersonAsmx.AsmxServiceSoap)(this)).QueryPersons(inValue);
            return retVal.Body.QueryPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DataLayer.SR_PersonAsmx.AsmxServiceSoap.BeginQueryPersons(DataLayer.SR_PersonAsmx.QueryPersonsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryPersons(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQueryPersons(System.AsyncCallback callback, object asyncState) {
            DataLayer.SR_PersonAsmx.QueryPersonsRequest inValue = new DataLayer.SR_PersonAsmx.QueryPersonsRequest();
            inValue.Body = new DataLayer.SR_PersonAsmx.QueryPersonsRequestBody();
            return ((DataLayer.SR_PersonAsmx.AsmxServiceSoap)(this)).BeginQueryPersons(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataLayer.SR_PersonAsmx.QueryPersonsResponse DataLayer.SR_PersonAsmx.AsmxServiceSoap.EndQueryPersons(System.IAsyncResult result) {
            return base.Channel.EndQueryPersons(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person> EndQueryPersons(System.IAsyncResult result) {
            DataLayer.SR_PersonAsmx.QueryPersonsResponse retVal = ((DataLayer.SR_PersonAsmx.AsmxServiceSoap)(this)).EndQueryPersons(result);
            return retVal.Body.QueryPersonsResult;
        }
        
        private System.IAsyncResult OnBeginQueryPersons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginQueryPersons(callback, asyncState);
        }
        
        private object[] OnEndQueryPersons(System.IAsyncResult result) {
            System.Collections.Generic.List<DataLayer.SR_PersonAsmx.Person> retVal = this.EndQueryPersons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryPersonsCompleted(object state) {
            if ((this.QueryPersonsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryPersonsCompleted(this, new QueryPersonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryPersonsAsync() {
            this.QueryPersonsAsync(null);
        }
        
        public void QueryPersonsAsync(object userState) {
            if ((this.onBeginQueryPersonsDelegate == null)) {
                this.onBeginQueryPersonsDelegate = new BeginOperationDelegate(this.OnBeginQueryPersons);
            }
            if ((this.onEndQueryPersonsDelegate == null)) {
                this.onEndQueryPersonsDelegate = new EndOperationDelegate(this.OnEndQueryPersons);
            }
            if ((this.onQueryPersonsCompletedDelegate == null)) {
                this.onQueryPersonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryPersonsCompleted);
            }
            base.InvokeAsync(this.onBeginQueryPersonsDelegate, null, this.onEndQueryPersonsDelegate, this.onQueryPersonsCompletedDelegate, userState);
        }
    }
}
